%{?scl:%scl_package python-coveralls}
%{!?scl:%global pkg_name %{name}}

%global srcname coveralls

Summary: Show coverage stats online via coveralls.io
Name: %{?scl_prefix}python-coveralls
Version: 1.1
Release: 0.1%{?dist}
Source0: https://pypi.python.org/packages/source/a/%{srcname}/%{srcname}-%{version}.tar.gz
License: MIT
Group: Development/Libraries
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
Prefix: %{_prefix}
BuildArch: noarch
Vendor: Ilya Baryshev <baryshev@gmail.com>
Url: http://github.com/coagulant/coveralls-python
BuildRequires:  %{?scl_prefix}python-devel
BuildRequires:  %{?scl_prefix}python-setuptools
Requires: %{?scl_prefix}python(abi)

%description
Coveralls for python
====================

`Coveralls.io`_ is service to publish your coverage stats online with a lot of `nice features`_.
This package provides seamless integration with ``coverage.py`` in your python projects.

.. _Coveralls.io: http://coveralls.io
.. _nice features: https://coveralls.io/features

How it works
------------
It makes custom report for data generated by ``coverage.py`` package and sends it to `json API`_ of coveralls.io service.
All python files in your coverage analysis are posted to this service along with coverage stats,
so please make sure you're not ruining your own security! For private projects there is `Coveralls Pro`_.

.. _json API: https://coveralls.io/docs/api_reference
.. _Coveralls Pro: https://coveralls.io/docs/pro

%prep
%setup -n %{srcname}-%{version}

%build
%{?scl:scl enable %{scl} "}
%{__python} setup.py build
%{?scl:"}

%install
%{__rm} -rf %{buildroot}
%{?scl:scl enable %{scl} "}
%{__python} setup.py install -O1 --skip-build --root %{buildroot}
%{?scl:"}

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-,root,root,-)
%attr(755,root,root) %{_bindir}/*
%{python_sitelib}/*
%doc CHANGELOG.rst LICENCE README.rst
#%doc build/*

%changelog
* Tue Dec  1 2015 Nico Kadel-Garcia <nkadel@skyhookireless.com> - 1.1-0.1
- Build SRPM from setup.py
- Activate python2.7 build and dependenies
