.PHONY:: testenv
testenv::
	#mock -r airflowrepo-6-x86_64 ../python-airflow16-srpm/airflowrepo-6-x86_64/python27-python-airflow16-*.src.rpm
	mock -r airflowrepo-6-x86_64 install python27-python-airflow16
	mock -r airflowrepo-6-x86_64 install python27-python-pip
	mock -r airflowrepo-6-x86_64 install yum sudo vim-minimal

